### ISSUE TITLE
Dependency on r-base?

### ISSUE THREAD

**Issue by michielbdejong** [edwin-de-jong/mnist-digits-as-stroke-sequences#4]
I downloaded R-Studio and when opening the IDE, got a warning that R is not installed. I found a forum post saying there is a package `r-base` for ubuntu (RStudio did work after installing that), might be worth documenting. Is it not possible to run those 3 lines of R from the command line - is installing an IDE necessary?

**Comment by edwin-de-jong** [comment]
Yes, R-Studio requires R, see the requirements:
https://www.rstudio.com/products/rstudio/download/

R studio is only mentioned as an example; other R environments, including command line versions, should work as well. An advantage of a graphical version is that the resulting sequences can be visualized. Especially for users who want to modify the stroke extraction approach (others could just as well download the dataset directly), this will be useful.
